### ISSUE TITLE
Looking for a Getting Started Wiki

### ISSUE THREAD

**Issue by raghu-nanda** [janmbaco/go-reverseproxy-ssl#23]
Great project.

I am looking forward to reviewing go-reverseproxy-ssl

Please help

**Comment by janmbaco** [comment]
Hello
Thank you for your interest in the project.
To use go-reverse-proxy to serve as a proxy you would have to create a configuration file and pass it as an argument in the call for example.
I have two services, (1) a website that I have hosted on an internal server called "example_web", and (2) a grpc server hosted on "example_grpc". I created the configuration file as follows:
```
{
	"web_virtual_hosts": [
		{
			"from": "www.example.com",
			"scheme": "http",
			"host_name": "esample_web",
			"port": 4200
		}
	],
	"grpc_web_virtual_hosts": [
		{
			"from": "www.example.com/api/v1",
			"scheme": "http",
			"host_name": "example_grpc",
			"port": 7000,
			"is_transparent_server": true,
			"allow_all_origins": true,
			"use_web_sockets": true
		}
	],
	"default_host": "www.example.com",
	"reverse_proxy_port": ":443",
	"log_console_level": 0,
	"log_file_level": 2,
	"logs_dir": "./logs"
}
```
Then I use a Dockerfile to create the server proxy:
```
FROM janmbaco/go-reverseproxy-ssl:latest

WORKDIR /app

COPY config.json .

EXPOSE 80
EXPOSE 443

CMD  [ "./go-reverseproxy-ssl", "-config", "config.json" ]
```
If you really like the project, consider contribute.
Greetings,

**Comment by raghu-nanda** [comment]
Hi, I want to build a replay proxy for testing automation. I need your help. 

The idea is to dump the http requests and replay them to test automations etc. 
Scope: Sites with https/http 
Media: api/images/js/html (a-to-z)

Approximate Example:
https://docs.mitmproxy.org/stable/mitmproxytutorial-replayrequests/

1) First of all is it possible?
2) Is it fun?
3) Let us do this? 

Affectionately,
R

**Comment by janmbaco** [comment]
Hi, 
Go-ReverseProxy-SSL is more suited for allowing secured access to an internal network from a node in a DMZ.
You can make a replay proxy based on for using  [Go-Infrastructure Server](https://github.com/janmbaco/go-infrastructure/tree/master/server) in the same way Go-ReverseProxy-SSL uses it.

Should you need tailored support, you can make use of the sponsor button.

**Comment by raghu-nanda** [comment]
Mm.. interesting .. Ok.

On the first note:

I am trying to run the Dockerfile with your config. I can understand I am missing some steps. I spent some time digging, but I wish to share with you. I don't need grps at this stage. I just want to run an end-to-end example. 

If time permits, let me know if we can setup a meeting/introduction or you can share me a demo video. 

My Skills: Golang(4/5), Linux(3/5), Docker(3/5), SSL (3/5)

This is my part-time project. 

Following is the first error that I got when I am running: 
```
panic: http: multiple registrations for www.example.com/ [recovered]
        panic: http: multiple registrations for www.example.com/

goroutine 1 [running]:
github.com/janmbaco/go-infrastructure/errors.(*errorThrower).Throw(0xc0001ae730, 0xc9a2c0, 0xc0001bf0b0)
        /home/runner/go/pkg/mod/github.com/janmbaco/go-infrastructure@v1.0.11/errors/errorthrower.go:22 +0x9c
github.com/janmbaco/go-infrastructure/errors.(*errorDefer).TryThrowError(0xc000075140)
        /home/runner/go/pkg/mod/github.com/janmbaco/go-infrastructure@v1.0.11/errors/errordefer.go:37 +0x162
panic(0xacef40, 0xc0001af4f0)
        /opt/hostedtoolcache/go/1.16.6/x64/src/runtime/panic.go:965 +0x1b9
net/http.(*ServeMux).Handle(0xc000039d40, 0xc0001c4410, 0x10, 0xc9bd60, 0xbfa950)
        /opt/hostedtoolcache/go/1.16.6/x64/src/net/http/server.go:2444 +0x2c5
net/http.(*ServeMux).HandleFunc(...)
        /opt/hostedtoolcache/go/1.16.6/x64/src/net/http/server.go:2481
main.reverseProxy.func1(0xaae320, 0xc000178180, 0xc000100b90)
        /home/runner/work/go-reverseproxy-ssl/go-reverseproxy-ssl/main.go:145 +0x3df
github.com/janmbaco/go-infrastructure/server.(*listenerBuilder).GetListener(0xc0001867e0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/janmbaco/go-infrastructure@v1.0.11/server/listener_builder.go:55 +0xdc
main.main()
        /home/runner/work/go-reverseproxy-ssl/go-reverseproxy-ssl/main.go:65 +0x5c2
```

**Comment by janmbaco** [comment]
Hi!!

This is a sample code obtained and modified for another project.

The problem is that the "from" in the first virtual host is as the "default_host" of proxy. Every "from" in the virtual host have to been diferent among them  and different with the "default_host".  Like this:

```
{
	"web_virtual_hosts": [
		{
			"from": "www.example.com",
			"scheme": "http",
			"host_name": "esample_web",
			"port": 4200
		}
	],
	"grpc_web_virtual_hosts": [
		{
			"from": "www.example.com/api/v1",
			"scheme": "http",
			"host_name": "example_grpc",
			"port": 7000,
			"is_transparent_server": true,
			"allow_all_origins": true,
			"use_web_sockets": true
		}
	],
	"default_host": "proxy.example.com",
	"reverse_proxy_port": ":443",
	"log_console_level": 0,
	"log_file_level": 2,
	"logs_dir": "./logs"
}
```
Anyway, this project is not a "replay proxy". 

You can make a replay proxy based on for using [Go-Infrastructure Server](https://github.com/janmbaco/go-infrastructure/tree/master/server) in the same way Go-ReverseProxy-SSL uses it.

Should you need tailored support, you can make use of the sponsor button.
